In [34]:
#Joining or Concatenating two 1D arrays

import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90])

arr3=np.concatenate((arr1,arr2))
print('arr3: ',arr3)

arr3:  [10 20 30 40 50 60 70 80 90]


In [9]:
#Joining or Concatenating two 2D arrays along row and columns

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[10,20,30],[40,50,60]])

arr3=np.concatenate((arr1,arr2),axis=1)
print('Concatenating along rows:')
print(arr3)

arr4=np.concatenate((arr1,arr2),axis=0)
print('Concatenating along columns:')
print(arr4)


Concatenating along rows:
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
Concatenating along columns:
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [16]:
#Stacking along rows and columns. By default axis is set to 0
"""
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
"""
#Concatenating along rows:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.stack((arr1, arr2), axis=1)
print(arr3)

#Concatenating along columns:
arr4 = np.stack((arr1, arr2)) #Here nothing is specified. so Axis=0
print(arr4)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [23]:
#Stacking with helper functions,hstack and vstack

#hstack: Stacks along rows
arr1 = np.array([10, 22, 33])
arr2 = np.array([40, 52, 63])
arr3=np.hstack((arr1,arr2))
print(arr3)

#hstack: Stacks along rows
arr3=np.vstack((arr1,arr2))
print(arr3)

arr4=np.array([[1,2,3],[4,5,6]])
arr5=np.array([[10,20,30],[40,50,60]])

arr6=np.hstack((arr4,arr5))
print(arr6)

arr7=np.vstack((arr4,arr5))
print(arr7)


[10 22 33 40 52 63]
[[10 22 33]
 [40 52 63]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [17]:
#Stacking along height using dstack. This works like normal stacking when axis is set to 1

arr4=np.dstack((arr1,arr2))
print(arr4)


[[[1 4]
  [2 5]
  [3 6]]]


In [19]:
arr5=np.stack((arr1,arr2),axis=1)
print(arr5)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
#Splitting 1D arrays
arr1 = np.array([11, 22, 33, 44, 55, 66,77,88,99,111,222,333])
arr2 = np.array_split(arr1, 4)

print(arr2)
print(arr2[0])
print(arr2[1])
print(arr2[2])
print(arr2[3])

[array([11, 22, 33]), array([44, 55, 66]), array([77, 88, 99]), array([111, 222, 333])]
[11 22 33]
[44 55 66]
[77 88 99]
[111 222 333]


In [33]:
#Splitting 2D arrays
arr1 = np.array([[20, 30], [40, 50], [60, 70], [80, 90], [100, 110], [120, 130]])
arr2 = np.array_split(arr1, 2)

print(arr2)
print(arr2[0])
print(arr2[1])


[array([[20, 30],
       [40, 50],
       [60, 70]]), array([[ 80,  90],
       [100, 110],
       [120, 130]])]
[[20 30]
 [40 50]
 [60 70]]
[[ 80  90]
 [100 110]
 [120 130]]


In [37]:
#Splitting along an axis
arr1 = np.array([[20, 30], [40, 50], [60, 70], [80, 90], [100, 110], [120, 130]])
arr2 = np.array_split(arr1, 2,axis=1)

print(arr2)

arr2 = np.array_split(arr1, 2,axis=0)

print(arr2)


[array([[ 20],
       [ 40],
       [ 60],
       [ 80],
       [100],
       [120]]), array([[ 30],
       [ 50],
       [ 70],
       [ 90],
       [110],
       [130]])]
[array([[20, 30],
       [40, 50],
       [60, 70]]), array([[ 80,  90],
       [100, 110],
       [120, 130]])]


In [43]:
#hsplit,vsplit
arr3=np.hsplit(arr1,2)
print("hsplit:")
print(arr3)

arr3=np.vsplit(arr1,2)
print("vsplit:")
print(arr3)

hsplit:
[array([[ 20],
       [ 40],
       [ 60],
       [ 80],
       [100],
       [120]]), array([[ 30],
       [ 50],
       [ 70],
       [ 90],
       [110],
       [130]])]
vsplit:
[array([[20, 30],
       [40, 50],
       [60, 70]]), array([[ 80,  90],
       [100, 110],
       [120, 130]])]


In [48]:
#Iterating through arrays
for x in arr3:
  print(x)

arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for z in arr3D:
  print(z)

[[20 30]
 [40 50]
 [60 70]]
[[ 80  90]
 [100 110]
 [120 130]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [47]:
#Iterating on each scalar element for 1d,2d arrays

for x in arr1:
 for y in x:
    print(y)

for x in arr3:
 for y in x:
    print(y)

20
30
40
50
60
70
80
90
100
110
120
130
[20 30]
[40 50]
[60 70]
[80 90]
[100 110]
[120 130]


In [51]:
#Iterating on scalar elements for 3d arrays:

print(arr3D)

for x in arr3D:
  for y in x:
    for z in y:
      print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [56]:
#Alternative to using for loops for iterating through scalar elements:
for x in np.nditer(arr3D):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [57]:
"""
Enumeration means mentioning sequence number of somethings one by one.

For getting corresponding index of the element while iterating, the ndenumerate() method can be used
"""
for idx, x in np.ndenumerate(arr3D):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [59]:
for idx, x in np.ndenumerate(arr1):
  print(idx, x)

(0, 0) 20
(0, 1) 30
(1, 0) 40
(1, 1) 50
(2, 0) 60
(2, 1) 70
(3, 0) 80
(3, 1) 90
(4, 0) 100
(4, 1) 110
(5, 0) 120
(5, 1) 130


In [60]:
arr1D=np.array([3,4,5,6,7])
for idx,x in np.ndenumerate(arr1D):
    print(idx,x)

(0,) 3
(1,) 4
(2,) 5
(3,) 6
(4,) 7


In [67]:
#Sorting arrays:
arr=np.array([5,2,1,2,5,7,9,192,34,7])
print(np.sort(arr))

arr2D=np.array([[11,2,45],[45,12,5]])
print(np.sort(arr2D))

arrStr=np.array(["banana","zebra","apples","giraffes"])
print(np.sort(arrStr))


[  1   2   2   5   5   7   7   9  34 192]
[[ 2 11 45]
 [ 5 12 45]]
['apples' 'banana' 'giraffes' 'zebra']


In [73]:
#Addition,Subtraction,Multiplication,Division of matrices
arr1=np.array([10,10,10,10,10])
arr2=np.array([20,30,40,50,60])
print('Addition: ',arr1+arr2)
print('Subtraction: ',arr1-arr2)
print('Multiplication: ',arr1*arr2)
print('Division: ',arr1/arr2)
print('Double Mul:',arr2**2)

Addition:  [30 40 50 60 70]
Subtraction:  [-10 -20 -30 -40 -50]
Multiplication:  [200 300 400 500 600]
Division:  [0.5        0.33333333 0.25       0.2        0.16666667]
Double Mul: [ 400  900 1600 2500 3600]


In [76]:
#Sin,Cos values
print(np.sin(arr1))
print(np.cos(arr1))

[-0.54402111 -0.54402111 -0.54402111 -0.54402111 -0.54402111]
[-0.83907153 -0.83907153 -0.83907153 -0.83907153 -0.83907153]


In [77]:
#Searching
arr2=np.array([20,30,40,50,60,200,400,600,800])

print(np.where(arr2%2==0))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)


In [78]:
print(np.where(arr2%2==1))

(array([], dtype=int64),)


In [79]:
print(np.where(arr2==20))

(array([0], dtype=int64),)


In [82]:
#Getting max,min,sum
print(arr2)
print(np.max(arr2))
print(np.min(arr2))
print(np.sum(arr2))

[ 20  30  40  50  60 200 400 600 800]
800
20
2200


In [87]:
#Getting max,min along an axis
arr2=np.array([[10,2,20],[5,60,12]])
print(arr2)
print(np.max(arr2,axis=0))
print(np.max(arr2,axis=1))

[[10  2 20]
 [ 5 60 12]]
[10 60 20]
[20 60]
